#pragma once
#include "apollo_msgs/msg/apollocanbus_lexus.hpp"
#include "rclcpp/rclcpp.hpp"
#include "nlohmann/json.hpp"
#include "cyber/common/log.h"
#include "adapter/serialization/std_msgs/header.hpp"
#include <string>
#include "adapter/serialization/apollo_msgs/apollocanbus_hazard_lights_rpt214.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_steering_cmd12c.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_dash_controls_right_rpt210.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_dash_controls_left_cmd10c.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_steering_rpt22c.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_turn_aux_rpt330.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_headlight_rpt218.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_hazard_lights_cmd114.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_dash_controls_left_rpt20c.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_headlight_aux_rpt318.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_dash_controls_right_cmd110.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_wiper_cmd134.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_wiper_rpt234.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_turn_rpt230.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_headlight_cmd118.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_door_rpt417.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_component_rpt20.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_wheel_speed_rpt407.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_steering_motor_rpt3406.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_steering_motor_rpt2405.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_steering_motor_rpt1404.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_brake_motor_rpt3403.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_brake_motor_rpt2402.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_brake_motor_rpt1401.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_wiper_aux_rpt334.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_shift_aux_rpt328.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_accel_rpt200.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_brake_rpt204.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_horn_cmd11c.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_global_rpt10.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_accel_aux_rpt300.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_cruise_control_buttons_rpt208.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_vehicle_speed_rpt400.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_brake_aux_rpt304.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_media_controls_cmd120.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_cruise_control_buttons_cmd108.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_parking_brake_cmd124.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_horn_rpt21c.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_shift_rpt228.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_shift_cmd128.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_accel_cmd100.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_parking_brake_rpt224.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_brake_cmd104.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_media_controls_rpt220.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_steering_aux_rpt32c.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_lat_lon_heading_rpt40e.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_yaw_rate_rpt40d.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_date_time_rpt40f.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_vin_rpt414.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_occupancy_rpt415.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_interior_lights_rpt416.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_turn_cmd130.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_detected_object_rpt411.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_veh_specific_rpt1412.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_veh_dynamics_rpt413.hpp"
#include "adapter/serialization/apollo_msgs/apollocanbus_rear_lights_rpt418.hpp"
namespace apollo_msgs::msg {
    nlohmann::json to_json (const ApollocanbusLexus &msg) ;
    ApollocanbusLexus from_json_ApollocanbusLexus (nlohmann::json obj) ;
    template <>
    ApollocanbusLexus from_json<ApollocanbusLexus>(nlohmann::json obj);
    nlohmann::json &operator>>(nlohmann::json &os, ApollocanbusLexus &dt);
    std::ostream & operator<<(std::ostream & os, const ApollocanbusLexus & dt);
    close_after_if_not_null & operator<<(close_after_if_not_null & os, const ApollocanbusLexus & dt);
}
